Add support for watering reports.
dknowles2/pydrawise pull request #101
Opened 2023-12-02 22:18 UTC by thomaskistler

Add support for watering reports.

2023-12-03 23:09 UTC, dknowles2 requested changes

2023-12-04 06:53 UTC, thomaskistler commented on pydrawise/schema.py
> +    def _generate_next_value_(name, start, count, last_values):
Created a base class.

2023-12-04 06:53 UTC, thomaskistler commented on pydrawise/schema.py
> +class AdvancedProgramScopeEnum(Enum):
Hard to tell whether someone will be able to use it. I'm assuming it's there for a reason.

2023-12-04 06:54 UTC, thomaskistler commented on pydrawise/schema.py
> +class Unit:
Fixed. Cleaned up all the time, datetime, and duration issues as well.

2023-12-04 06:54 UTC, thomaskistler commented on pydrawise/schema.py
> +class RunEventType:
Fixed.

2023-12-04 06:56 UTC, thomaskistler commented on pydrawise/schema.py
> +    status: ControllerStatus = None
I did this for consistency reasons. This looks to be the convention throughout this file. There are many instances of required fields that have a default. If we want to go this route, we should probably clean it up everywhere.

2023-12-04 06:56 UTC, thomaskistler commented on pydrawise/client.py
> +                "controllers.permitted_program_start_times.application.zones",
Fixed.

2023-12-04 07:02 UTC, thomaskistler commented on pydrawise/schema.py
> +class RunStatusType:
This will only work if we concurrently update the graphql schema file. You ok with that?

2023-12-04 13:17 UTC, dknowles2 commented on pydrawise/schema.py
> +    status: ControllerStatus = None
If it needs a default, then it should create an empty `ControllerStatus`. It's a typing violation to assign `None` here as it's not marked optional.

If this is incorrect elsewhere here, let's fix that in a separate PR.

2023-12-04 13:18 UTC, dknowles2 commented on pydrawise/schema.py
> +class AdvancedProgramScopeEnum(Enum):
Another note here is that it's easy to add functionality when we find use-cases for it, but it's very hard to remove it.

2023-12-04 13:19 UTC, dknowles2 commented
Looks like there's merge conflicts that need to be addressed.

2023-12-06 05:24 UTC, thomaskistler commented
Resolved the merge conflict.

2023-12-06 16:03 UTC, thomaskistler commented
Don't land it yet. I think you were right in that I'm going to remove some of the fields and classes to only return the data that is potentially useful.

2023-12-16 18:15 UTC, thomaskistler commented
I have also started working on the migration from legacy api to new graphql api here: https://github.com/thomaskistler/home-assistant-core/pull/1. Before I start fixing the tests, please let me know whether this approach looks ok.

2023-12-17 16:41 UTC, dknowles2 commented
> I have also started working on the migration from legacy api to new graphql api in Home Assistant here: [thomaskistler/home-assistant-core#1](https://github.com/thomaskistler/home-assistant-core/pull/1). Before I start fixing the tests, please let me know whether this approach looks ok.

That looks really similar to what I had been working on: https://github.com/dknowles2/ha-core/commit/1b7bfcc527e09c64f887938b30e87c179c3b9754

Not sure if I'll have time in the next few weeks to get that reviewed, so feel free to send the PR upstream.

2023-12-17 16:41 UTC, dknowles2 approved these changes

2023-12-17 16:41 UTC, merged

2023-12-17 17:20 UTC, thomaskistler commented
Ok. I will merge the two and send them upstream.

Also, if you could cut a December release for pydrawise, that would be great. The most recent changes are required to integrate into HA.